steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'install','appengine-spring-boot/' ]
  - name: "gcr.io/cloud-builders/mvn"
    args: [ "package", "-Dmaven.test.skip=true" ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy","appengine-spring-boot/src/main/appengine/app.yaml" ]
    timeout: "1600s"