steps:
  - name: 'gcr.io/cloud-builders/mvn'
    dir: "appengine-spring-boot"
    args: [ 'package','-f','pom.xml','-Dmaven.test.skip=true' ]
#  - name: "gcr.io/cloud-builders/mvn"
#    args: [ "package", "-Dmaven.test.skip=true" ]
#  - name: 'gcr.io/cloud-builders/git'
#    args: [ 'clone', 'https://github.com/ajaykumar2014/google-cloud']
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "appengine-spring-boot"
    args: [ "app", "deploy","src/main/appengine/app.yaml" ]
    timeout: "1600s"