steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'package','-f','appengine-spring-boot/pom.xml','-Dmaven.test.skip=true' ]
#  - name: "gcr.io/cloud-builders/mvn"
#    args: [ "package", "-Dmaven.test.skip=true" ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy","src/main/appengine/app.yaml" ]
    timeout: "1600s"