    steps:
      - name: 'gcr.io/cloud-builders/mvn'
        dir: "appengine-spring-boot"
        #args: [ 'package','-f','pom.xml','-Dmaven.test.skip=true' ]
        args: [ 'clean', 'package']
      - name: 'gcr.io/cloud-builders/docker'
        dir: "appengine-spring-boot"
        args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/appengine-spring-boot/appengine-spring-boot:tag1', '.' ]
      - name: "gcr.io/cloud-builders/gcloud"
        dir: "appengine-spring-boot"
        args: [ "app", "deploy" ]
        timeout: "1600s"