steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: "appengine-spring-boot"
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/appengine-spring-boot:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: "appengine-spring-boot"
    args: ['push', 'gcr.io/$PROJECT_ID/appengine-spring-boot:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: "appengine-spring-boot"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'appengine-spring-boot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/appengine-spring-boot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
    - 'gcr.io/$PROJECT_ID/appengine-spring-boot:$COMMIT_SHA'